locals {
  name = "agent-launchpad"

  base_ingress_rules = [
    {
      description = "LQAM web"
      port_end    = 80
      port_start  = 80
      priority    = 1
      protocol    = "tcp"
      cidr_ip     = var.allowed_web_cidr
    },
    {
      description = "LQAM SSH"
      port_end    = 22
      port_start  = 22
      priority    = 1
      protocol    = "tcp"
      cidr_ip     = var.allowed_ssh_cidr
    },
  ]

  github_actions_ingress_rules = var.github_actions_ssh_cidr == "" ? [] : [
    {
      description = "GitHub Actions ephemeral SSH"
      port_end    = 22
      port_start  = 22
      priority    = 2
      protocol    = "tcp"
      cidr_ip     = var.github_actions_ssh_cidr
    },
  ]

  ingress_rules = concat(
    local.base_ingress_rules,
    local.github_actions_ingress_rules,
  )

  runtime_env = join("\n", [
    "# Generated by Terraform. Runtime secrets are supplied by the approved SSH deployment.",
    "PERSISTENCE_BACKEND=postgres",
    "AUTHORIZATION_MODE=local",
    ""
  ])
}

resource "byteplus_vpc" "launchpad" {
  vpc_name     = local.name
  description  = "VPC for the Liu Qi Agent Management starter kit"
  cidr_block   = "172.20.0.0/16"
  enable_ipv6  = false
  project_name = var.project_name

  tags {
    key   = "application"
    value = local.name
  }
}

resource "byteplus_subnet" "launchpad" {
  vpc_id      = byteplus_vpc.launchpad.id
  zone_id     = var.zone_id
  subnet_name = local.name
  description = "LQAM subnet"
  cidr_block  = "172.20.1.0/24"

  tags {
    key   = "application"
    value = local.name
  }
}

resource "byteplus_security_group" "launchpad" {
  vpc_id              = byteplus_vpc.launchpad.id
  security_group_name = local.name
  description         = "Web and SSH access for LQAM"
  project_name        = var.project_name

  tags {
    key   = "application"
    value = local.name
  }
}

resource "byteplus_security_group_rule" "ingress" {
  for_each = { for rule in local.ingress_rules : rule.description => rule }

  security_group_id = byteplus_security_group.launchpad.id
  direction         = "ingress"
  protocol          = each.value.protocol
  port_start        = each.value.port_start
  port_end          = each.value.port_end
  cidr_ip           = each.value.cidr_ip
  policy            = "accept"
  priority          = each.value.priority
  description       = each.value.description
}

resource "byteplus_security_group_rule" "egress" {
  security_group_id = byteplus_security_group.launchpad.id
  direction         = "egress"
  protocol          = "all"
  port_start        = -1
  port_end          = -1
  cidr_ip           = "0.0.0.0/0"
  policy            = "accept"
  priority          = 1
  description       = "Outbound access for Ark, Git and package registries"
}

resource "byteplus_ecs_instance" "launchpad" {
  instance_name                 = local.name
  host_name                     = "agent-launchpad"
  description                   = "Liu Qi Agent Management starter kit"
  project_name                  = var.project_name
  instance_charge_type          = "PostPaid"
  instance_type                 = var.instance_type
  spot_strategy                 = "NoSpot"
  zone_id                       = var.zone_id
  image_id                      = var.image_id
  key_pair_name                 = var.key_pair_name
  keep_image_credential         = false
  security_enhancement_strategy = "Active"
  subnet_id                     = byteplus_subnet.launchpad.id
  security_group_ids            = [byteplus_security_group.launchpad.id]
  system_volume_type            = "ESSD_PL0"
  system_volume_size            = 50

  user_data = base64encode(templatefile("${path.module}/cloud-init.yaml.tftpl", {
    repository_url  = var.repository_url
    repository_ref  = var.repository_ref
    runtime_env_b64 = base64encode(local.runtime_env)
  }))

  tags {
    key   = "application"
    value = local.name
  }
}

resource "byteplus_eip_address" "launchpad" {
  billing_type = "PostPaidByTraffic"
  bandwidth    = 5
  isp          = "BGP"
  name         = local.name
  description  = "Public IP for the Liu Qi Agent Management starter kit"
  project_name = var.project_name

  tags {
    key   = "application"
    value = local.name
  }
}

resource "byteplus_eip_associate" "launchpad" {
  allocation_id = byteplus_eip_address.launchpad.id
  instance_id   = byteplus_ecs_instance.launchpad.id
  instance_type = "EcsInstance"
}
